name: Test

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      slow_tests:
        description: 'Run slow tests'
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - uses: isort/isort-action@master
        with:
          isortVersion: "5.10.1"
          configuration: "--profile black --check-only --diff"
          sortPaths: "stackerlberg"
      - uses: psf/black@stable
        with:
          src: "stackerlberg"
      - name: Install dependencies
        run: pip install -e ".[tests,format]"
      - name: Run tests
        run: if ${{ inputs.slow_tests || false }}; then pytest --rootdir . ; else pytest -m "not slow" --rootdir . ; fi
